/* ===== /v91inj:ledger/ CM-3 因果/伏笔账本（纯数据；elda content causality 读取核销；不改引擎） =====
 * 字段：id / type(伏笔|设定|人物|地点|事件) / desc / plant(埋设锚点) / reap(回收锚点) / status(open|closed) / world(所属卷/域)
 * 锚点语法：flag:<flag名> = 该 flag 在 src 中被 effects 写入；node:<节点id> = 节点存在且被 go/then 引用；其余按关键词词频。
 */
window.CAUSALITY_LEDGER = [
  {id:"led_01", type:"设定", desc:"金秤家族血脉与隐秘历史，贯穿全书的核心家族线", plant:"金秤", reap:"node:tm_negotiate", status:"open", world:"金秤线"},
  {id:"led_02", type:"设定", desc:"晨天城为东境故都，地图标准中的东境中枢（BD-4 经 east_chengtian_old 故都线核销）", plant:"晨天", reap:"node:east_chengtian_old", status:"closed", world:"东境"},
  {id:"led_03", type:"人物", desc:"鬃吼为兽王，兽人草原的最高意志", plant:"鬃吼", reap:"node:orc_deep_totem", status:"open", world:"兽人草原"},
  {id:"led_04", type:"人物", desc:"腐光为暗蚀会首领，净化令阴影后的操盘者", plant:"腐光", reap:"node:tm_ruins", status:"open", world:"暗蚀线"},
  {id:"led_05", type:"人物", desc:"秦·长风，北境名将/东境系关键人物，铁门关对峙主角", plant:"秦·长风", reap:"node:tm_negotiate", status:"open", world:"铁门关"},
  {id:"led_06", type:"设定", desc:"七枚锚，精灵与矮人共守的古老封印体系", plant:"七枚锚", reap:"node:elf_deep_council", status:"open", world:"精灵线"},
  {id:"led_07", type:"道具", desc:"铁牌，七枚锚的钥匙/凭证线，跨卷收集", plant:"铁牌", reap:"node:elf_deep_tower_entry", status:"open", world:"七锚线"},
  {id:"led_08", type:"伏笔", desc:"兽人神谕真伪，黑石部族与圣山信仰的核心悬念", plant:"神谕", reap:"flag:oracle_fake", status:"open", world:"兽人草原"},
  {id:"led_09", type:"人物", desc:"灰鬃，黑石部族狼骑兵长，挚友支线主角", plant:"node:orc_w_enter", reap:"node:orc_w_end", status:"open", world:"兽人草原"},
  {id:"led_10", type:"人物", desc:"林歌，银月祭坛见习祭司，挚友支线主角", plant:"node:elf_w_enter", reap:"node:elf_w_end", status:"open", world:"精灵线"},
  {id:"led_11", type:"地点", desc:"银月祭坛，精灵月池所在，净根仪式主场", plant:"银月", reap:"node:elf_deep_altar", status:"open", world:"精灵线"},
  {id:"led_12", type:"事件", desc:"铁门关战争，东境与北境的前线对峙", plant:"铁门关", reap:"node:tm_negotiate", status:"open", world:"铁门关"},
  {id:"led_13", type:"地点", desc:"圣山图腾林，兽人祖灵信仰之地", plant:"圣山", reap:"node:orc_deep_totem", status:"open", world:"兽人草原"},
  {id:"led_14", type:"势力", desc:"狼旗，兽人草原部族联盟的旗帜", plant:"狼旗", reap:"node:orc_deep_gate", status:"open", world:"兽人草原"},
  {id:"led_15", type:"地点", desc:"月池，精灵祭坛核心，树根腐化的观测点", plant:"月池", reap:"node:elf_deep_altar", status:"open", world:"精灵线"},
  {id:"led_16", type:"伏笔", desc:"世界树根腐化，银月祭坛异变的源头", plant:"树根", reap:"node:elf_w_end", status:"open", world:"精灵线"},
  {id:"led_17", type:"地点", desc:"祖灵洞，兽人圣山深处的传承之地", plant:"祖灵", reap:"node:orc_w_end", status:"open", world:"兽人草原"},
  {id:"led_18", type:"人物", desc:"大汗，黑石部族之主，草原权力顶点", plant:"大汗", reap:"flag:khan_aware", status:"open", world:"兽人草原"},
  {id:"led_19", type:"人物", desc:"青叶长老，林歌师父，树根真相的知情者", plant:"青叶", reap:"node:elf_w_step2", status:"open", world:"精灵线"},
  {id:"led_20", type:"事件", desc:"净化令，光明教会清扫异端的法令与暗蚀线总纲", plant:"净化令", reap:"node:tm_refugee", status:"open", world:"净化令线"},
  {id:"led_21", type:"势力", desc:"白袍教会，圣光信仰与净化令的执行者", plant:"白袍", reap:"node:tm_frontline", status:"open", world:"净化令线"},
  {id:"led_22", type:"伏笔", desc:"铁门关和谈，秦·长风与东军的终局抉择", plant:"node:tm_frontline", reap:"node:tm_negotiate", status:"open", world:"铁门关"},
  {id:"led_23", type:"伏笔", desc:"识破假神谕，巫医帐信任与草原变革的钥匙", plant:"node:orc_deep_witch", reap:"flag:oracle_fake", status:"open", world:"兽人草原"},
  {id:"led_24", type:"因果", desc:"放过劫匪，善念在矮人王都的余响", plant:"flag:spared_robber", reap:"node:dwarf_deep_bard", status:"open", world:"矮人线"},
  {id:"led_25", type:"因果", desc:"手刃匪首，杀伐之名传遍前线", plant:"flag:bandit_leader_killed", reap:"node:tm_ruins", status:"open", world:"铁门关"},
  {id:"led_26", type:"因果", desc:"散尽家财济难民，关南难民营记得这张脸", plant:"flag:gave_all_to_refugees", reap:"node:tm_refugee", status:"open", world:"铁门关"},
  {id:"led_27", type:"因果", desc:"拒绝父亲给出的真相，身世线走向独自承担", plant:"flag:father_truth_denied", reap:"node:tm_watchtower", status:"open", world:"身世线"},
  {id:"led_28", type:"因果", desc:"违抗预言，命运线与圣山神谕的对抗", plant:"flag:prophecy_defied", reap:"node:orc_deep_totem", status:"open", world:"兽人草原"},
  {id:"led_29", type:"因果", desc:"背叛同窗，学院线的代价与割裂", plant:"flag:betrayed_classmate", reap:"node:elf_deep_council", status:"open", world:"学院线"},
  {id:"led_30", type:"因果", desc:"解放水岸，南方水岸线的高光转折", plant:"flag:aquan_liberated", reap:"node:tm_negotiate", status:"open", world:"南方线"},
  {id:"led_31", type:"因果", desc:"放走信使，情报线上的一次仁慈", plant:"flag:let_mercury_go", reap:"node:tm_courier", status:"open", world:"铁门关"},
  {id:"led_32", type:"地点", desc:"东境晨天城，帝京文脉与铁门关外的故土（BD-4 经 east_chengtian_old 故都线核销）", plant:"node:tm_refugee", reap:"node:east_chengtian_old", status:"closed", world:"东境"},
  {id:"led_33", type:"事件", desc:"兽人草原入局，外乡人踏进黑石部族", plant:"node:orc_deep_gate", reap:"node:orc_deep_leave", status:"open", world:"兽人草原"},
  {id:"led_34", type:"事件", desc:"精灵王庭入局，银叶集市的第一印象", plant:"node:elf_deep_market", reap:"node:elf_deep_council", status:"open", world:"精灵线"},
  {id:"led_35", type:"地点", desc:"矮人王都铁砧议会，八百年的锤声", plant:"node:dwarf_deep_hall", reap:"node:dwarf_deep_mine2", status:"open", world:"矮人线"},
  {id:"led_36", type:"伏笔", desc:"西境元素风暴异常：风暴间隔缩短、风暴眼蓝光游走、枯井泉水与地下裂缝相通，与元素行者/封魔之战旧史呼应（BD-1 新埋）。", plant:"node:west_storm_observatory", reap:"future", status:"open", world:"西境"},
  {id:"led_37", type:"伏笔", desc:"死亡沙漠第七封印柱松动：盐湖渗水、夜车取水、遗迹壁画的凿柱笔记，与 seal 深渊封印松动（day200）同源呼应（BD-2 新埋）。", plant:"node:desert_seal_watch", reap:"future", status:"open", world:"死亡沙漠"},
  {id:"led_38", type:"伏笔", desc:"圣城圣痕司地基下发现与沙漠第七柱同源的石柱（艾德蒙叔叔遗信），圣城与沙漠压在一条封印线上（BD-3 新埋）。", plant:"node:church_doubter2", reap:"future", status:"open", world:"光明教会"},

  {id:"led_sp8_01", type:"设定", desc:"西境游侠学院（院长柯恩，铁木黑弓，鹰牌信物）", plant:"node:sp8_ranger_00", reap:"node:sp8_ranger_14", status:"open", world:"西境"},
  {id:"led_sp8_02", type:"伏笔", desc:"柯恩身世：军阀火并中失去村子的孤儿收容者", plant:"node:sp8_ranger_00b", reap:"node:sp8_ranger_15", status:"open", world:"西境"},
  {id:"led_sp8_03", type:"人物", desc:"游侠公会老会长（行省会鹰旗持有者）", plant:"node:sp8_ranger_14", reap:"node:sp8_ranger_15", status:"open", world:"西境"},

  {id:"led_a1_01", type:"设定", desc:"理想线·富甲天下：商路第一步与第一桶金", plant:"node:goal_intro_wealth", reap:"node:goal_wealth_3", status:"open", world:"理想线"},
  {id:"led_a1_02", type:"设定", desc:"理想线·威震四海：老佣兵授艺与第一场硬仗", plant:"node:goal_intro_might", reap:"node:goal_might_3", status:"open", world:"理想线"},
  {id:"led_a1_03", type:"设定", desc:"理想线·守护苍生：孤儿二狗与货栈救火", plant:"node:goal_intro_guard", reap:"node:goal_guard_3", status:"open", world:"理想线"},
  {id:"led_a1_04", type:"设定", desc:"理想线·探寻真相：《封印前史》残卷与七印草图", plant:"node:goal_intro_truth", reap:"node:goal_truth_3", status:"open", world:"理想线"},
  {id:"led_a1_05", type:"设定", desc:"理想线·自由自在：雪原独行与雪崩村守望", plant:"node:goal_intro_free", reap:"node:goal_free_3", status:"open", world:"理想线"},
  {id:"led_a1_06", type:"设定", desc:"理想线·登临神座：符文石板参悟与第一缕微光", plant:"node:goal_intro_god", reap:"node:goal_god_3", status:"open", world:"理想线"},
  {id:"led_a1_07", type:"设定", desc:"理想线·名留青史：救人扬名与吟游诗人的传唱", plant:"node:goal_intro_fame", reap:"node:goal_fame_3", status:"open", world:"理想线"},
  {id:"led_a1_08", type:"设定", desc:"理想线·以血还血：旧伤溯源与刀鞘刻名", plant:"node:goal_intro_revenge", reap:"node:goal_revenge_3", status:"open", world:"理想线"},
    {id:"led_b5_01",type:"道具",desc:"钥匙收集线：矿洞铜牌+元素池底黑铁+金库失窃铁牌，皆旧封印之钥（acad_magic_y1_pool / acad_story_vault）",plant:"acad_magic_y1_pool",reap:"acad_magic_y5_choice",status:"open",world:"vol_academy"},
    {id:"led_b5_02",type:"伏笔",desc:"封印之门位于北境地脉蛇头·第三哨；门缝青光渐亮，封印松动（seal 主线弱呼应）",plant:"acad_magic_y3_seal",reap:"north_road_1",status:"open",world:"vol_academy"},
    {id:"led_b5_03",type:"人物",desc:"金先生（金秤的金），老莫里茨之师，地脉学派五人小团体领袖，失踪；墓园无字碑即其葬地",plant:"acad_story_oldman",reap:"acad_story_graveyard",status:"open",world:"vol_academy"},
    {id:"led_b5_04",type:"人物",desc:"艾琳·霜叶，北境民谣歌者，旧礼堂歌声、荣誉墙墨叉、档案被涂，与教会异端调查有关",plant:"acad_story_ghost",reap:"acad_story_archives",status:"open",world:"vol_academy"},
    {id:"led_b5_05",type:"伏笔",desc:"费尔曼与六钥匙：刘矿头死于矿洞、老铁守第三哨失踪；费尔曼手背青纹更深",plant:"acad_magic_y5_ferman",reap:"north_road_1",status:"open",world:"vol_academy"},
    {id:"led_b5_06",type:"地点",desc:"第三哨铜钟，十年未鸣；守钟人独臂老兵言敲钟会出事",plant:"acad_magic_y4_quiet",reap:"north_road_1",status:"open",world:"vol_academy"},
    {id:"led_b5_07",type:"人物",desc:"陆昭（鸦羽），炼金系偷铁牌者，休学去南，灰楼夜火持铁盒再现，铁盒或已交费尔曼",plant:"acad_story_vault_end",reap:"acad_story_fire_after",status:"open",world:"vol_academy"},
    {id:"led_b5_08",type:"人物",desc:"秦策，东境承天城演武场之约；东境动荡避风北上，秦·长风线人物网络延伸",plant:"acad_story_duel_after",reap:"east_chengtian_old",status:"open",world:"vol_academy"},
    {id:"led_frontier_01",type:"地点",desc:"第三哨城，联盟最北军事要塞。铜钟铭文刻七锚之图，地脉蛇头在此，七锚之约第一环。",plant:"frontier_bell_4",reap:"frontier_bell_5",status:"open",world:"vol_north"},
    {id:"led_frontier_02",type:"伏笔",desc:"老周之子三十年前在矿洞失踪，尸首未寻；失踪前曾说钟底下那个东西在叫他。",plant:"frontier_old_2",reap:"frontier_old_5",status:"open",world:"vol_north"},
    {id:"led_frontier_03",type:"伏笔",desc:"矿洞封洞二十年仍传出水声，矿工旧物沉在巷道深处，锚2所在。",plant:"frontier_mine_gate",reap:"frontier_mine_1",status:"open",world:"vol_north"},
    {id:"led_frontier_04",type:"伏笔",desc:"雪原狼群由黑皮两足人影指挥，狼王悬赏与城门告示同图。",plant:"frontier_infirmary",reap:"frontier_ev_wolves",status:"open",world:"vol_north"},
    {id:"led_frontier_05",type:"人物",desc:"独臂军需官，掌矿洞钥匙与铜钟旧事，知七锚铭文来历。",plant:"frontier_sergeant",reap:"frontier_bell_4",status:"open",world:"vol_north"},
    {id:"led_frontier_06",type:"伏笔",desc:"王三失踪于钟楼，雪地留下首枚铁牌，与钟身刻痕同纹（方牌中竖纹），七锚之首。",plant:"frontier_bell_2",reap:"frontier_bell_3",status:"open",world:"vol_north"},
    {id:"led_frontier_07",type:"伏笔",desc:"风洞铁皮棺材：黑皮人组织运送，棺内传出敲击声，与矿洞水声同源；风洞深处另有铁门需钥匙。",plant:"frontier_tie_6",reap:"frontier_tie_8",status:"open",world:"vol_north"},
    {id:"led_frontier_08",type:"人物",desc:"老铁：第三哨老兵，其父三十年前死于矿洞，遗物铁牌被矿上收走；手上有风洞铁门钥匙。",plant:"frontier_tie_1",reap:"frontier_tie_7",status:"open",world:"vol_north"},
    {id:"led_frontier_09",type:"伏笔",desc:"黑纹伤病：被咬老兵伤口渗黑纹，做同一个敲击噩梦，指向矿洞方向；军医宋记录在册。",plant:"frontier_medic_2",reap:"frontier_medic_5",status:"open",world:"vol_north"},
    {id:"led_frontier_10",type:"地点",desc:"地窖裂缝：第三哨地底深渊地脉，seal 主线 day200 联动；玩家侧加固/观望/上报教会三路影响文本。",plant:"frontier_seal_1",reap:"frontier_seal_after_2",status:"open",world:"vol_north"},
    {id:"led_a3_01",type:"伏笔",desc:"北境灰烬村废墟之眼（深渊生物窥视）",plant:"origin_expand_north_edge",reap:"origin_expand_north_6",status:"open",world:"vol_north"},
    {id:"led_a3_02",type:"设定",desc:"南方深海绿光·第七印在海底（商船线）",plant:"origin_expand_south_4",reap:"",status:"open",world:"vol_south"},
    {id:"led_a3_03",type:"人物",desc:"杜嬷嬷送阿禾东去承天城投奔姓秦者（教会孤儿线）",plant:"origin_expand_church_4",reap:"",status:"open",world:"vol_church"},
    {id:"led_a3_04",type:"设定",desc:"世界树根部封印·晨星之泪可洗蚀痕（精灵线）",plant:"origin_expand_elf_6",reap:"",status:"open",world:"vol_elf"},
    {id:"led_a3_05",type:"设定",desc:"矮人南矿洞铁门·七道封印之一（矮人线）",plant:"origin_expand_dwarf_4",reap:"",status:"open",world:"vol_dwarf"},
    {id:"led_a3_06",type:"人物",desc:"铁门关斥候托信交汇城李管事·暗蚀会挖地寻物（兽人线）",plant:"origin_expand_orc_7",reap:"",status:"open",world:"vol_orc"},
    {id:"led_a3_07",type:"人物",desc:"秦·长风：晨天城秦氏幸存者，居交汇城，官署暗探在找（东境线）",plant:"origin_expand_east_7",reap:"",status:"open",world:"vol_east"},
    {id:"led_a3_08",type:"伏笔",desc:"承天城井水变浑·晨天城覆灭征兆重现",plant:"origin_expand_east_6",reap:"",status:"open",world:"vol_east"},
    {id:"led_b1_01",type:"设定",desc:"学院入学引导链：自由城/王都/铁门关前线三入口可达学院（acad_road_1~5），开学典礼埋塔灯传说",plant:"acad_road_1",reap:"academy_admission",status:"open",world:"vol_academy"},
    {id:"led_b1_02",type:"伏笔",desc:"塔顶之灯数人之说（acad_tower_rumor）与图书馆塔灯呼应，待学院线回收",plant:"acad_road_4",reap:"academy_graduation",status:"open",world:"vol_academy"},
    {id:"led_b2_01",type:"设定",desc:"学院五学年生活线（acad_life_y1~y5，30 节点：课程ifJob/宿舍/同窗/期中/期末/假期/学年事件），north_academy_gate 生活区入口",plant:"acad_life_y1_open",reap:"academy_graduation",status:"open",world:"vol_academy"},
    {id:"led_b2_02",type:"伏笔",desc:"费尔曼教授=席恩（看守者），禁书区夜课、净化令、第七节点钥匙（acad_brass_key）",plant:"acad_life_y2_friend",reap:"academy_elda_forbidden_1",status:"open",world:"vol_academy"},
    {id:"led_b3_01",type:"人物",desc:"学院人际网：塞西莉娅（东境政务/晨天水）/灰须·莫里（矮人符文/铁门七封印）/伊莲娜（精灵治愈/忘忧草）/老铁（铁门关铁匠），各 4 节点闭环",plant:"acad_people_hub",reap:"academy_graduation",status:"open",world:"vol_academy"},
    {id:"led_b3_02",type:"人物",desc:"导师四人（墨丘利银叶/戈拉铁门关铁片/特蕾莎枯木/老莫里茨商路），各 2 节点闭环",plant:"acad_mentor_hub",reap:"academy_graduation",status:"open",world:"vol_academy"},
{id:"led_grad_01",type:"伏笔",desc:"老莫里茨临终托付——北境封印与七锚的真相入口，金秤家守墓人身份初现",plant:"grad_stay_4",reap:"anchor_grave_1",status:"open",world:"vol_academy"},
{id:"led_grad_02",type:"伏笔",desc:"金秤家信物铁牌（三道弧线围一圆），老莫里茨遗赠，墓园认亲凭证",plant:"grad_stay_4",reap:"anchor_grave_1",status:"open",world:"vol_academy"},
{id:"led_grad_03",type:"伏笔",desc:"费尔曼第三把锈钥匙——禁书区铁门钥匙，留校线持有",plant:"grad_y3_end_3",reap:"anchor_vault_1",status:"open",world:"vol_academy"},
{id:"led_grad_04",type:"设定",desc:"墓园无字碑·金先生=金秤家守墓人，碑下埋锚（第三哨北）",plant:"grad_stay_5",reap:"anchor_grave_1",status:"open",world:"vol_academy"},
{id:"led_grad_05",type:"设定",desc:"毕业四去向（留校/从军/游历/回乡），各自独立链与北上汇合点",plant:"grad_choose",reap:"grad_path_stay_north",status:"closed",world:"vol_academy"},
{id:"led_alumni_01",type:"伏笔",desc:"狼群南迁与神谕石林枯井水眼干涸，洛克线埋下兽人神谕危机",plant:"alumni_rock_4",reap:"anchor_oracle_1",status:"open",world:"vol_academy"},
{id:"led_alumni_02",type:"伏笔",desc:"铁门关防务疏漏与第三哨异动，凯恩线指向北境战争前兆",plant:"alumni_kain_4",reap:"warphase_1",status:"open",world:"vol_academy"},
{id:"led_alumni_03",type:"伏笔",desc:"《灰烬之书》失窃与圣痕司异动，艾丽丝线指向圣痕与封纹",plant:"alumni_alice_4",reap:"anchor_church_1",status:"open",world:"vol_academy"},
{id:"led_alumni_04",type:"伏笔",desc:"神谕枯井井底壁画与波浪纹刻痕，阿塔线标记地底通路",plant:"alumni_ata_3",reap:"anchor_oracle_1",status:"open",world:"vol_academy"},
{id:"led_alumni_05",type:"伏笔",desc:"东境灰瘟与地底铁门铰链，洛卡线指向沉埋门扉",plant:"alumni_loka_4",reap:"anchor_mine_1",status:"open",world:"vol_academy"},
{id:"led_alumni_06",type:"伏笔",desc:"晨天故城与官仓粮印旧账，塞西莉娅线指向东境地下",plant:"alumni_cecy_4",reap:"anchor_chen_1",status:"open",world:"vol_academy"},
{id:"led_alumni_07",type:"伏笔",desc:"矮人矿洞石室与标路记号，莫里线呼应神谕枯井波浪纹",plant:"alumni_mori_5",reap:"anchor_mine_1",status:"open",world:"vol_academy"},
{id:"led_alumni_08",type:"伏笔",desc:"圣痕封伤与封纹铁片，艾琳娜线指向净仪与圣痕司隐秘",plant:"alumni_elena_4",reap:"anchor_church_1",status:"open",world:"vol_academy"},
{id:"led_alumni_09",type:"伏笔",desc:"铜钟裂口与钟楼铁板地图，老铁线标记北境地下门扉",plant:"alumni_tie_3",reap:"anchor_tower_1",status:"open",world:"vol_academy"},
{id:"led_alumni_10",type:"伏笔",desc:"导师遗物黄铜钥匙与七块铁碑文，指向七锚封镇真相",plant:"grad_mentor_3",reap:"goldscale_1",status:"open",world:"vol_academy"},
{id:"led_anchor_01",type:"伏笔",desc:"七锚之首·哨楼锚：铜叶与半枚铁牌，守钟人传承",plant:"anchor_tower_1",reap:"anchor_finale_1",status:"open",world:"vol_north"},
{id:"led_anchor_02",type:"伏笔",desc:"七锚之二·矿洞锚：铁门铁牌与锚形铜印，刘矿头旧线",plant:"anchor_mine_1",reap:"anchor_finale_1",status:"open",world:"vol_north"},
{id:"led_anchor_03",type:"伏笔",desc:"七锚之三·墓园锚：无字碑下锚形玉印，金秤守门人三代",plant:"anchor_grave_1",reap:"anchor_finale_1",status:"open",world:"vol_north"},
{id:"led_anchor_04",type:"伏笔",desc:"七锚之四·学院金库锚：铁锚印与陆昭失窃铁牌，指向承天城",plant:"anchor_vault_1",reap:"anchor_finale_1",status:"open",world:"vol_academy"},
{id:"led_anchor_05",type:"伏笔",desc:"七锚之五·晨天故都锚：天衡殿铜印，陆昭持学院铁牌合印",plant:"anchor_chen_1",reap:"anchor_finale_1",status:"open",world:"vol_east"},
{id:"led_anchor_06",type:"伏笔",desc:"七锚之六·教会圣库锚：圣痕司圣物库铁印，守库人已叛",plant:"anchor_church_1",reap:"anchor_finale_1",status:"open",world:"vol_church"},
{id:"led_anchor_07",type:"伏笔",desc:"七锚之七·兽人神谕锚：神谕石林石印，白狼低头认主",plant:"anchor_oracle_1",reap:"anchor_finale_1",status:"open",world:"vol_race"},
{id:"led_goldscale_01",type:"设定",desc:"金秤=晨天王朝司秤官金家传世镇器，两头挂一头称天一头称地",plant:"goldscale_1",reap:"goldscale_8",status:"open",world:"vol_north"},
{id:"led_goldscale_02",type:"设定",desc:"金家守秤三十一代，金望之等持锚人三十一年",plant:"goldscale_2",reap:"goldscale_7",status:"open",world:"vol_north"},
{id:"led_goldscale_03",type:"伏笔",desc:"金望之第三十代守秤人临终托付秤账与铁牌",plant:"goldscale_3",reap:"goldscale_8",status:"open",world:"vol_north"},
{id:"led_goldscale_04",type:"伏笔",desc:"晨天王朝天衡殿主簿金秤镇界记载：锚足齐则秤稳",plant:"goldscale_5",reap:"goldscale_8",status:"open",world:"vol_east"},
{id:"led_war_01",type:"伏笔",desc:"北境七阶段战争线：边境摩擦至终战，战火由北向南烧遍大陆",plant:"warphase_1",reap:"warphase_14",status:"open",world:"vol_war"},
{id:"led_fac_01",type:"设定",desc:"四阵营互斥：加入一方后其余阵营声望下降，背叛走惩罚支线",plant:"faction_free_1",reap:"faction_traitor_4",status:"open",world:"vol_war"},
{id:"led_fac_02",type:"伏笔",desc:"教会的铁匠旧案：二十年前渎神罪烧死打钥匙的铁匠，与七锚钥匙线呼应",plant:"faction_church_5",reap:"anchor_tower_1",status:"open",world:"vol_church"},
{id:"led_fac_03",type:"伏笔",desc:"沙漠遗迹玉片：刻痕像半个锚，地缝符号与学院禁书区同源",plant:"faction_desert_5",reap:"anchor_mine_1",status:"open",world:"vol_desert"},
{id:"led_fac_04",type:"设定",desc:"商会盐道：自由城商会以军饷换北境盐道畅通，商会立场成型",plant:"faction_free_5",reap:"faction_free_9",status:"open",world:"vol_free"}

];
/* ===== /v91inj:ledger:end/ ===== */

/* ===== /v91inj:ledgerwords/ CM-3 设定词冻结表（elda ci 第 19 检查器：每词必须在其所属域出现） ===== */
window.CAUSALITY_WORDS = [
  {word:"金秤", world:"金秤线", file:"script_02a.js"},
  {word:"晨天", world:"东境", file:"script_02.js"},
  {word:"鬃吼", world:"兽人草原", file:"dn_orc_deep.js"},
  {word:"腐光", world:"暗蚀线", file:"script_02b.js"},
  {word:"秦·长风", world:"铁门关", file:"script_02d.js"},
  {word:"七枚锚", world:"精灵线", file:"dn_elf_dwarf.js"},
  {word:"铁牌", world:"七锚线", file:"script_02.js"},
  {word:"神谕", world:"兽人草原", file:"script_02.js"},
  {word:"灰鬃", world:"兽人草原", file:"dn_orc_deep.js"},
  {word:"林歌", world:"精灵线", file:"dn_elf_dwarf.js"},
  {word:"银月", world:"精灵线", file:"script_02.js"},
  {word:"铁门关", world:"铁门关", file:"script_02.js"},
  {word:"圣山", world:"兽人草原", file:"script_02.js"},
  {word:"狼旗", world:"兽人草原", file:"script_02d.js"},
  {word:"月池", world:"精灵线", file:"dn_elf_dwarf.js"},
  {word:"树根", world:"精灵线", file:"script_02e.js"},
  {word:"祖灵", world:"兽人草原", file:"script_02a.js"},
  {word:"大汗", world:"兽人草原", file:"script_02a.js"},
  {word:"青叶", world:"精灵线", file:"dn_elf_dwarf.js"},
  {word:"净化令", world:"净化令线", file:"script_02g.js"}
];
/* ===== /v91inj:ledgerwords:end/ ===== */
