/* =========================================================================
 * dn_echo.js — E-1/E-2 多年回响登记（超大型剧情八工程 · 工程 E）
 * 数据：微小选择 → 多年后在场景节点带出回响句（CoG「离别礼物数年后出现」）
 * 机制：v93e2_echoLine(node) 只读注入（见 script_03.js /e2inj:echohook/）
 *       命中 = node.id ∈ echoAt 且 S.flags[flag] 已置 → 注入 tpl 段
 * 铁律：只读 S.flags；不改变节点语义/选项/判定；开关 S.settings.echoLine（默认 true）
 * 文风：V66 白描；禁 30 治理词；中文引号成对
 * ========================================================================= */
window.ECHO_TRACKS = [
/* ---- 组 A · 自由城/故地回响（商人线、信物、旧选择） ---- */
{id:"echo_merchant_saved",   flag:"merchant_saved",   echoAt:["fc_tavern","grad_roam_1","anchor_finale_1"], tpl:["那个被你从刀口下救出的皮货商人，后来逢人就说自由城有个好管闲事的年轻人。他铺子门口挂了你没要的那只鹿皮钱袋，风一吹就晃。"]},
{id:"echo_merchant_reported",flag:"merchant_reported",echoAt:["fc_tavern","grad_roam_1"], tpl:["告发那晚的事，你早忘了细节。可自由城码头的行商们没忘——从那以后，他们看你的眼神总带着三分防备。"]},
{id:"echo_gamble_lost",      flag:"gamble_lost",      echoAt:["fc_tavern","grad_free"], tpl:["当年赌场输掉的那把，多年后竟在某个醉汉嘴里听成了一段传奇。你没纠正。有些输，比赢更值得留着。"]},
{id:"echo_gambler",          flag:"gambler",          echoAt:["fc_tavern","warphase_9"], tpl:["赌桌上养出来的直觉救过你几回。这世上大多数事，押注之前先看庄家脸色——那是自由城教会你的第一课。"]},
{id:"echo_letter_taken",     flag:"letter_taken",     echoAt:["fc_tavern","grad_home_1"], tpl:["那封没送出去的信还在你行囊最底层，纸角磨得起毛。收信人是谁，你已经记不真切，只记得那天风很大。"]},
{id:"echo_home_fc",          flag:"home_fc",          echoAt:["grad_home_1","anchor_finale_5"], tpl:["自由城邦的钟楼是你认路的标记。走得再远，夜里听见那种钟声，你还是会下意识放慢脚步。"]},
{id:"echo_oldwolf_met",      flag:"oldwolf_met",      echoAt:["grad_roam_1","fc_tavern"], tpl:["老狼头说过，狼老了会离开狼群自己走。你后来在北境的雪地里见过一次孤狼，想起他，想起他说这话时的眼神。"]},
{id:"echo_senlin_legend",    flag:"senlin_legend",    echoAt:["grad_roam_1","alumni_ata_1"], tpl:["森林里那段传说，你在篝火边给不下十个人讲过。每讲一次，细节就多一分。讲到最后，连你自己都分不清哪些是真的。"]},
{id:"echo_ivy_meet",         flag:"ivy_meet",         echoAt:["grad_home_1","alumni_alice_1"], tpl:["常春藤那姑娘后来去了哪，没人知道。只记得她临别时说你欠她一杯酒。这账，你一直记着。"]},
{id:"echo_forge_helped",     flag:"forge_helped",     echoAt:["alumni_mori_1","warphase_11"], tpl:["铁匠铺里帮过的那把火，后来烧出了几柄好刀。锻刀的人记得你，刀上的钢纹也记得——那是你亲手拉的风箱。"]},
/* ---- 组 B · 学院/校友回响（墨丘利、塞拉芬、同学、入学） ---- */
{id:"echo_mercury_protege",  flag:"mercury_research_assistant", echoAt:["grad_ceremony","alumni_elena_1"], tpl:["墨丘利教授的研究笔记里，有一页专门记着你的名字。他从不夸人，只在你离开后，把那页折了角。"]},
{id:"echo_mercury_rejected", flag:"mercury_note_rejected", echoAt:["grad_ceremony","alumni_alice_1"], tpl:["那封退回的纸条，墨丘利收在讲台抽屉里。多年后整理旧物的人发现，纸上的字迹已经淡得几乎看不见。"]},
{id:"echo_mercury_hurt",     flag:"mercury_hurt_deeply", echoAt:["grad_ceremony"], tpl:["你伤过墨丘利一次。他说重话时脸是平静的，可手一直在抖。那之后他再没让你进过他的私人书房。"]},
{id:"echo_seraphine_name",   flag:"seraphine_name_volunteered", echoAt:["grad_ceremony","alumni_cecy_1"], tpl:["塞拉芬的名字是你取的。她后来在信里说，这是她这辈子收到的头一件像样的礼物。信末落款处画了只歪歪扭扭的鸟。"]},
{id:"echo_admission_done",   flag:"admission_done",   echoAt:["grad_ceremony","north_academy_gate"], tpl:["入学那天的雪很大。你站在学院山门前，雪落在肩头，把新发的校徽盖了一层白。如今徽章上的珐琅已经磨掉了漆。"]},
{id:"echo_feel_note_done",   flag:"feel_note_done",   echoAt:["grad_choice","alumni_alice_1"], tpl:["那首写在纸背上的小诗，你在毕业前夜塞进了图书馆某本书里。不知后来谁翻到了它，只听说书页间夹着的那页，折痕特别深。"]},
{id:"echo_classmate_cecilia",flag:"classmate_cecilia_alive", echoAt:["alumni_cecy_1","grad_farewell"], tpl:["塞西莉娅还活着。这个消息在你心里搁了许多年，每次想起，都像按住一道旧伤——不疼，但你知道它在。"]},
{id:"echo_classmate_alex",   flag:"classmate_alex_alive", echoAt:["alumni_rock_1","grad_farewell"], tpl:["亚历克斯后来在信里说，那天要是没有你，他可能走不出那条巷子。信纸上有水渍，他说是下雨。"]},
{id:"echo_classmate_mary",   flag:"classmate_mary_alive", echoAt:["alumni_ata_1","grad_farewell"], tpl:["玛丽学会用左手写字了。她说右手再也拿不起笔的时候，想起了你当年教她的那句话——路不止一条。"]},
{id:"echo_awakening_done",   flag:"awakening_done",   echoAt:["grad_ceremony","north_library"], tpl:["觉醒那夜的光，你记了很多年。图书馆的灯火、指尖的灼热、还有窗外那棵老树投下的影子——它们都还在原地。"]},
{id:"echo_origin_profile",   flag:"origin_profile_done", echoAt:["grad_home_1","anchor_finale_6"], tpl:["你出发那天，村里人送你的干粮袋早就空了。可袋子上那根系口绳，你还留着，磨得发亮。"]},
{id:"echo_darkcult_evidence",flag:"darkcult_evidence", echoAt:["grad_army_3","warphase_6"], tpl:["暗教那份名单，你抄过一份藏在身上。多年后它成了某些人谋生的凭据，而你始终没说这东西打哪儿来。"]},
{id:"echo_darkcult_slain",   flag:"darkcult_captain_slain", echoAt:["warphase_6","warphase_14"], tpl:["暗教船长死在你手里的那晚，甲板上的火光照得海面通红。那场火后来被编进歌谣，唱到第三段就把你写成了英雄。"]},
{id:"echo_soul_exposed",     flag:"soul_exposed",     echoAt:["grad_ceremony","alumni_elena_1"], tpl:["灵魂暴露的事，知情者寥寥。但每次有人盯着你多看两眼，你都会想起那面照出底细的镜子。"]},
{id:"echo_church_wanted",    flag:"church_wanted",    echoAt:["grad_holy","warphase_3"], tpl:["教会通缉你的告示贴过半个圣城。后来风头过去，告示被人揭走，据说拿去垫了锅。你倒希望那是真的。"]},
{id:"track_east_wanted",     flag:"east_wanted",      echoAt:["grad_home_3","warphase_4"], tpl:["东境的通缉文书你见过一眼，画像画得不像。可悬赏数字你记得——那大概是东境人给过你的最高评价。"]},
/* ---- 组 C · 战争回响（北境、银穗、兽人、铁门关） ---- */
{id:"echo_north_intel",      flag:"north_intel_done", echoAt:["warphase_3","warphase_10"], tpl:["北境那份情报，是你用一匹马换来的。后来战局几次翻转，都绕着那页纸上的地名打转。"]},
{id:"echo_silver_invite",    flag:"silver_invite",    echoAt:["warphase_5","grad_army_2"], tpl:["银穗商路那次邀请，你最终没赴约。可对方记了你的好，每逢开战，总有人替你传一句口信——银穗欠你一次。"]},
{id:"echo_beijing_saved",    flag:"beijing_saved",    echoAt:["warphase_7","grad_home_4"], tpl:["你救下的那座边城，城墙上如今刻着守城将士的名字。第一个名字是别人的，但城中老人说，该刻的另有其人。"]},
{id:"echo_helped_fugitive",  flag:"helped_fugitive",  echoAt:["warphase_8","grad_army_4"], tpl:["那个你藏过的逃兵，后来成了铁门关有名的排长。他每逢酒醉就讲当年有个陌生人救了他，讲得眉飞色舞。"]},
{id:"echo_mysterious_elder", flag:"mysterious_elder", echoAt:["warphase_10","anchor_oracle_1"], tpl:["神秘老者说过的话，你在战场上应验过三次。每次都应验在他预言的位置——可你再也没见过他。"]},
{id:"echo_seal2_khan_dead",  flag:"seal2_khan_dead",  echoAt:["warphase_12","alumni_ata_1"], tpl:["可汗死后的那几年，草原乱了又平。你见过新可汗点兵，阵势齐整，可再也没有当年那种让大地发抖的脚步声。"]},
{id:"echo_seal2_khan_alive", flag:"seal2_khan_alive", echoAt:["warphase_12","alumni_ata_1"], tpl:["老可汗还活着。他托人带过一句话给你——草原记得你的名字。带话的人说，可汗说这话时，手里握着那柄旧弯刀。"]},
{id:"echo_seal3_queen",      flag:"seal3_queen_freed",echoAt:["warphase_13","alumni_elena_1"], tpl:["精灵女王重获自由那日，林海下了整夜细雨。雨停后，精灵们把她的名字刻回古树上，字迹新得像刚发芽。"]},
{id:"echo_east_blacksmoke",  flag:"east_blacksmoke",  echoAt:["warphase_4","grad_home_4"], tpl:["东境的黑烟，你在梦里又见过一次。醒来后你记不清是哪座城，只记得烟里混着铁锈和焦木的气味。"]},
{id:"echo_eclipse_infiltrator", flag:"eclipse_infiltrator", echoAt:["warphase_14","anchor_finale_4"], tpl:["蚀组织把你当自己人用了好几年。你离开那天，他们给的名册上，你的代号后面画了个问号。"]},
{id:"echo_eclipse_kill",     flag:"eclipse_kill_success", echoAt:["warphase_14","anchor_finale_5"], tpl:["那次刺杀之后，你的名字进了某些人的黑账。你从不提那晚，可每次听见刀出鞘的声音，手指都会先于意识绷紧。"]},
/* ---- 组 D · 终局/七锚/神谕回响 ---- */
{id:"echo_god_favor",        flag:"god_favor",        echoAt:["anchor_finale_1","anchor_oracle_1"], tpl:["神明眷顾过你一次。那之后你总在午夜醒来，觉得窗外的风里站着谁，站了很久，又走了。"]},
{id:"echo_rexa_vow",         flag:"rexa_vow",         echoAt:["anchor_finale_4","anchor_chen_1"], tpl:["雷克萨的誓言，你在城墙上听他立过。多年后他成了守城人，而誓言像一道旧疤，长进了这座城的砖缝里。"]},
{id:"echo_cecilia_secret",   flag:"cecilia_secret",   echoAt:["anchor_finale_4","anchor_chen_4"], tpl:["塞西莉娅的秘密，你替她守了半生。晨天故都的地砖下压着的东西，你只在那夜见过一次，之后连方向都没再辨过。"]},
{id:"echo_elara_ally",       flag:"elara_ally",       echoAt:["anchor_finale_2","alumni_elena_1"], tpl:["伊莱拉成了你在这片大陆上最稳的一条线。她传信从不用暗语，因为她知道你看得懂她的字迹。"]},
{id:"echo_thorin_ally",      flag:"thorin_ally",      echoAt:["anchor_finale_2","alumni_mori_1"], tpl:["索林那锤子，你帮忙抡过一回。后来他打的兵器上都留了个不起眼的记号，说是给你的回礼。"]},
{id:"echo_luna_accepted",    flag:"luna_accepted",    echoAt:["anchor_finale_3","alumni_ata_1"], tpl:["露娜接纳你那天，月下的湖面很静。她没说话，只把一枚狼牙放在你掌心——那是草原上最重的信物。"]},
{id:"echo_kai_accepted",     flag:"kai_accepted",     echoAt:["anchor_finale_3","alumni_rock_1"], tpl:["凯的拥抱撞得你肋骨发疼。他说从今天起，你就是他的兄弟。后来他在信里叫了你七年哥。"]},
{id:"echo_sophia_awakened",  flag:"sophia_awakened",  echoAt:["anchor_finale_3","alumni_alice_1"], tpl:["索菲娅觉醒那夜，学院塔楼的窗全亮了。她隔窗冲你喊了一句什么，被风卷走了，你没听清，但一直记得那个轮廓。"]},
{id:"echo_felix_ally",       flag:"felix_ally",       echoAt:["anchor_finale_2","grad_army_1"], tpl:["费利克斯欠你一次救命之恩。他把这事记在佩剑的剑鞘内衬上，说剑在，债在。"]},
{id:"echo_aria_fear",        flag:"aria_fear",        echoAt:["anchor_finale_3","alumni_elena_1"], tpl:["阿丽亚怕过你。那点怕意后来被时间磨平，可她见你时眼里的光，总比见别人时收着三分。"]},
{id:"echo_dragon_bonded",    flag:"dragon_bonded",    echoAt:["anchor_finale_4","anchor_finale_6"], tpl:["龙选择你那年，你才明白什么叫'被记住'。它记得你的气味、你的心跳，还有你第一次摸它鳞片时手抖的样子。"]},
{id:"echo_dragon_trust",     flag:"dragon_trust",     echoAt:["anchor_finale_4"], tpl:["龙的信任像山，给出去就收不回。它在高空盘旋等你的时候，影子落在地上，比任何旗帜都醒目。"]},
{id:"echo_giant_friend",     flag:"giant_friend",     echoAt:["anchor_finale_4","warphase_13"], tpl:["巨人把你举到肩上看过日落。从那以后，你对'高处的风'有了不同的理解——那是巨人眼里的世界。"]},
{id:"echo_seal1_repaired",   flag:"seal1_repaired",   echoAt:["anchor_finale_4","anchor_mine_1"], tpl:["第一道封印是你亲手修好的。石料合拢那刻，地脉的震颤停了一瞬，像大地在应答。"]},
{id:"echo_seal5_fixed",      flag:"seal5_fixed",      echoAt:["anchor_finale_4"], tpl:["第五道封印补上的时候，你听见极深极远的地方传来一声叹息。没人信你，可那声音在你耳朵里住了很多年。"]},
{id:"echo_seal6_sacrifice",  flag:"seal6_sacrifice",  echoAt:["anchor_finale_4","anchor_chen_5"], tpl:["第六道封印是用代价换的。你从来没对人说过代价是什么，只是每次经过那座祭坛，都会绕路。"]},
{id:"echo_v50_merchant_scale", flag:"v50_商人_金秤学徒", echoAt:["anchor_finale_5","anchor_finale_6"], tpl:["金秤学徒的名号，你担了半生。商人们敬你，也怕你——因为你心里那杆秤，从不为谁倾斜。"]},
{id:"echo_v50_priest_crown", flag:"v50_牧师_加冕",    echoAt:["anchor_finale_5"], tpl:["加冕那天的钟声，圣城响了九十九下。你戴冠时手很稳，可后来你总梦见那顶冠掉在雪地里。"]},
{id:"echo_v50_knight_oath",  flag:"v50_骑士_旧誓",    echoAt:["anchor_finale_5","warphase_14"], tpl:["旧日誓言你还背得出来。每次战前念它，都像在念自己的名字——时间久了，誓言和人就分不开了。"]},
{id:"echo_v50_mage_truth",   flag:"v50_法师_神陨真相", echoAt:["anchor_finale_5","north_library"], tpl:["神陨的真相你查到了，可那真相像一块烧红的铁，握不住也放不下。你把它写进书里，又在最后一页犹豫了整夜。"]},
{id:"echo_v50_warrior_flag", flag:"v50_战士_战旗七战", echoAt:["anchor_finale_5","warphase_14"], tpl:["那面战旗跟了你七场硬仗。第七场之后，你把它卷起来收进箱底——旗上的弹孔比星星还密。"]},
{id:"echo_v50_ranger_forest",flag:"v50_游侠_与林同在", echoAt:["anchor_finale_5","alumni_elena_1"], tpl:["你答应过森林的事，一件都没忘。林间的路认得你的脚印，风替你记着那些没说出口的诺言。"]},
{id:"echo_v50_rogue_light",  flag:"v50_盗贼_影入光",  echoAt:["anchor_finale_5","grad_free"], tpl:["从影子里走到光下的那天，你花了很多年。如今你走在大街上，影子还是比你慢半步——它在等你回头。"]},
{id:"echo_v50_sorc_seed",    flag:"v50_术士_留下火种", echoAt:["anchor_finale_5","north_library"], tpl:["你留下的火种，后来在学院的旧壁炉里烧了好几个冬天。接过火的人不认识你，但记得你留的话。"]},
{id:"echo_v50_soul_legis",   flag:"v50_灵法_灵界立法", echoAt:["anchor_finale_5","anchor_chen_6"], tpl:["灵界的律法是你立的头几条。立完那夜，亡灵们排队从你门前过，没有一只开口——那是它们能给的最高敬意。"]},
/* ---- 组 E · 七锚/晨天/帝国回响 ---- */
{id:"echo_medici_heir",      flag:"medici_heir",      echoAt:["anchor_chen_1","alumni_cecy_1"], tpl:["梅迪奇家的继承人身份，你揣了很久。晨天故都的老人们提起梅迪奇，眼神里有敬畏，也有别的东西——你没细问。"]},
{id:"echo_ivy_seen",         flag:"ivy_seen",         echoAt:["anchor_chen_2","alumni_cecy_1"], tpl:["晨天的城墙上爬满常春藤。你每次看见它，都会想起那个也叫常春藤的人，想起她说过的一句没头没尾的话。"]},
{id:"echo_watched",          flag:"watched",          echoAt:["anchor_chen_3","anchor_finale_1"], tpl:["你知道有人在看你。那种被注视的感觉像一根细线，牵着你的后颈，从晨天一直跟到雪原。"]},
{id:"echo_mercury_crack",    flag:"mercury_crack_seen_deep", echoAt:["anchor_finale_4","north_library"], tpl:["墨丘利看到的裂隙，你也看到了。那裂缝比所有人以为的都深——深到能听见另一头有东西在呼吸。"]},
{id:"echo_eclipse_contacted",flag:"eclipse_contacted", echoAt:["anchor_finale_4","warphase_14"], tpl:["蚀组织接触你的那次会面，在第七码头一间仓库里。桌上只有一盏灯和一张地图，地图上画着七个点。"]},
{id:"echo_owns_airship",     flag:"owns_airship",     echoAt:["anchor_finale_2","warphase_8"], tpl:["那艘飞空艇，你给它取的名字至今没人念对过。它老得叮当响，可每次升空，你还是会站到船头去。"]},
{id:"echo_dragon_found",     flag:"dragon_found",     echoAt:["anchor_finale_2","alumni_rock_1"], tpl:["找到龙的那天，山里的雾散得特别快。龙从雾里走出来，像一堵移动的墙，而你居然没躲。"]},
{id:"echo_giant_found",      flag:"giant_found",      echoAt:["anchor_finale_2","warphase_13"], tpl:["巨人坐在山谷里等了你三天。它说有人告诉它，会有一个背旧剑的人来。那个人是你。"]},
{id:"echo_seal1_visited",    flag:"seal1_visited",    echoAt:["anchor_mine_1","anchor_finale_4"], tpl:["第一道封印旧址，你回去看过一次。石头上你当年刻的记号还在，被风磨浅了，但还认得出。"]},
{id:"echo_desert_visited",   flag:"desert_visited",   echoAt:["anchor_mine_1","grad_roam_2"], tpl:["沙漠你去过一次，沙子就记住了你的脚印。后来有人在那片沙里捡到过一枚刻着你名字的铜牌，问遍商队没人认领。"]},
{id:"echo_merchant_pressed", flag:"mercury_pressed_too_hard", echoAt:["grad_ceremony"], tpl:["你把墨丘利逼得太紧的那回，他说了句'够了'。那两个字后来在你耳边响过很多次，每次都比上一次响。"]},
/* ---- 组 F · 学院专精/日常回响（v51 分支 + 情感） ---- */
{id:"echo_mage_elemental",   flag:"v51_魔法师_elemental_1", echoAt:["grad_ceremony","north_library"], tpl:["元素课第一节，导师让你把火苗捧在掌心。你练到指尖起泡才学会。如今你随手就能点起一堆篝火，可总记得第一次的烫。"]},
{id:"echo_mage_arcane",      flag:"v51_魔法师_arcane_1", echoAt:["grad_ceremony","north_library"], tpl:["奥术的纹路在你眼里已经成了第二语言。你读魔法书不用逐字看，扫一眼就知道这页有没有陷阱。"]},
{id:"echo_soul_medium",      flag:"v51_灵魂法师_medium_1", echoAt:["grad_ceremony","anchor_chen_6"], tpl:["通灵人这行当，你入行是因为好奇。后来你发现，听见亡者说话不难，难的是替他们保守秘密。"]},
{id:"echo_soul_soulbinder",  flag:"v51_灵魂法师_soulbinder_1", echoAt:["grad_ceremony","anchor_finale_5"], tpl:["缚魂术教你明白了一件事：灵魂的重量比羽毛轻，比山重。你给不少人系过最后一根线，也剪断过。"]},
{id:"echo_sorc_alchemist",   flag:"v51_术士_alchemist_1", echoAt:["grad_ceremony","alumni_mori_1"], tpl:["炼金炉的火焰你看了十年。这行当教会你耐心——有的东西要烧够时辰，早了晚了都不成。"]},
{id:"echo_sorc_selfproof",   flag:"v50_术士_自证",    echoAt:["anchor_finale_5","grad_ceremony"], tpl:["自证那场试炼，你赢得并不漂亮，但很彻底。从那以后没人再拿你的出身说事——他们改说你的手段。"]},
{id:"echo_soul_formal",      flag:"v50_灵法_要正式",  echoAt:["anchor_finale_5","grad_ceremony"], tpl:["你坚持要个正式名分那回，灵界的长老们沉默了很久。最后他们给了，却没说这决定重不重要。"]},
{id:"echo_mage_freescholar", flag:"v50_法师_自由学者", echoAt:["anchor_finale_5","north_library"], tpl:["自由学者的日子清苦，但你从不后悔。没人管你的书单，也没人管你的研究方向——那比什么都值钱。"]},
{id:"echo_priest_noct",      flag:"v50_牧师_光照无祷", echoAt:["anchor_finale_5","grad_holy"], tpl:["不祷告也能引来光，这件事你自己琢磨了很久。后来你明白了：光本来就不挑人。"]},
{id:"echo_knight_humanlock", flag:"v50_骑士_人即锁",  echoAt:["anchor_finale_5","warphase_14"], tpl:["你把誓言系在人身上，而不是教条上。这让你在骑士团里显得格格不入，也让你在战场上从没丢过一个人。"]},
{id:"echo_warrior_flagonly", flag:"v50_战士_旗不孤",  echoAt:["anchor_finale_5","warphase_14"], tpl:["战旗不孤——这是你后来才懂的话。旗在人在，旗倒人散。你保住了那面旗，也保住了跟着旗走的人。"]},
{id:"echo_ranger_path",      flag:"v50_游侠_林是路",  echoAt:["anchor_finale_5","alumni_elena_1"], tpl:["林是路，不是墙。你年轻时总想穿过它，后来学会沿着它走，再后来，你成了路的一部分。"]},
{id:"echo_rogue_shadow",     flag:"v50_盗贼_影同行",  echoAt:["anchor_finale_5","grad_free"], tpl:["影子陪了你很多年。你学会不讨厌它、不甩掉它，后来还学会了让影子替你办事。"]},
{id:"echo_merchant_fair",    flag:"v50_商人_先守后分", echoAt:["anchor_finale_5","anchor_finale_6"], tpl:["先守住，再分——这是金秤教你的第一课。你守着守着，发现'分'比'守'难得多。"]},
/* ---- 组 G · 中立状态回响（线索/盟约类，触发条件宽松） ---- */
{id:"echo_cooperated",       flag:"cooperated",       echoAt:["warphase_8","grad_army_4"], tpl:["你配合过的那次行动，事后没人提过你的名字。但领队的人在战后给你的信里写了句：记你一功。"]},
{id:"echo_watcher_invited",  flag:"watcher_invited",  echoAt:["anchor_chen_3","anchor_finale_4"], tpl:["守望者邀请过你。你没答应，也没拒绝——只是把那个徽章收进了贴身的袋子里。"]},
{id:"track_giant_helper",    flag:"giant_helper",     echoAt:["anchor_finale_2","warphase_13"], tpl:["你帮过巨人一次。巨人的记性比传说中好得多——它记得你的声音，隔老远就能认出来。"]},
{id:"echo_dragon_near",      flag:"dragon_near",      echoAt:["anchor_finale_2"], tpl:["龙在附近的时候，空气里有股硫磺和松脂混在一起的气味。你隔着山头就能闻到，然后心跳会快半拍。"]},
{id:"echo_medici_eclipse_suspect", flag:"medici_eclipse_suspect", echoAt:["anchor_chen_2","anchor_finale_4"], tpl:["梅迪奇和蚀组织之间那点牵连，你查过一阵就停了。有些线，扯到头会扯出一整匹布来。"]},
{id:"echo_mercury_impressed",flag:"mercury_impressed_by_intellect", echoAt:["grad_ceremony","north_library"], tpl:["墨丘利当众说过一次你聪明。就那一次，他后来不承认，可你记得他说话时点了一下头。"]},
{id:"track_mercury_disappointed", flag:"mercury_disappointed", echoAt:["grad_ceremony"], tpl:["墨丘利失望的时候不说话，只把眼镜摘下来擦。你见过两次，每次都觉得比挨骂还难受。"]},
{id:"echo_sector_lord",      flag:"sector_lord_encounter", echoAt:["warphase_7","grad_home_3"], tpl:["那个区块领主，你见过他一面。他看人的眼神像在称斤两——你当时就觉得，这人迟早会栽在秤上。"]}
,
/* ---- 组 F · 失败回响（F-3：失败不是终点，多年后还有人记得） ---- */
{id:"echo_fail_warwall",      flag:"f_failpath_warwall_liu",   echoAt:["fc_tavern","grad_army_1"], tpl:["铁门关军法官的名册后来换过三任。可你那个名字，总有人记得——不是记你的罪，是记你蹲过那间牢，还能走出去。"]},
{id:"echo_fail_raid",         flag:"f_failpath_raid_iron",     echoAt:["failrep_cove_3","warphase_5"], tpl:["雪原上的人认路子不认脸。你从冰裂隙活着回来的事，比你自己以为的传得更远——后来有商队愿意让你押头车，就因为这个。"]},
{id:"echo_fail_intel",        flag:"f_failpath_intel_zhao",    echoAt:["north_library","grad_ceremony"], tpl:["墨丘利那页注脚，你始终没还。多年后整理旧物的人在一本书里找到它，纸边磨得发白，像被人反复翻过。"]},
{id:"echo_fail_cell",         flag:"f_failrep_cell_done",      echoAt:["arrive_east_tiemen","anchor_finale_4"], tpl:["东墙下城的老赵后来逢人就说，铁门关有个年轻人替他把一句旧话带到了。他说的那句，你自己都快忘了。"]},
{id:"echo_fail_cove",         flag:"f_failrep_cove_done",      echoAt:["grad_roam_1","warphase_9"], tpl:["夜莺的信使后来散进各路。偶尔有人在篝火边说起那条商道上的信，就会有人补一句：那会儿有个从冰裂隙出来的人，也替他们跑过腿。"]}
];
